[package]
name = "bolt-rs"
version = "0.1.0"
edition = "2021"

[features]
default = ["client"]
client = ["dep:axum"]
validator = []

[dependencies]
serde_with = "2.0.1"
serde = "1.0.145"
serde_json = "1.0.85"
url = "2.3.1"
futures = "0.3.27"

[dependencies.axum]
version = "0.6.12"
optional = true

[dependencies.reqwest]
version = "0.11.0"
features = ["json", "multipart"]

[dev-dependencies]
tokio = { version = "1.26.0", features = ["test-util", "macros"] }
