[package]
name = "bolt-rs"
version = "0.3.0"
edition = "2021"

[features]
default = ["client"]
client = ["dep:tokio", "dep:warp"]
validator = []

[dependencies]
serde_with = "2.0.1"
serde = "1.0.145"
serde_json = "1.0.85"
url = "2.3.1"
tokio-test = "0.4.2"

## REQWEST ##
[dependencies.reqwest]
version = "0.11.0"
features = ["json", "multipart"]

[dependencies.tokio]
version = "1"
features = ["full"]
optional = true

[dependencies.warp]
version = "0.3"
optional = true
