[package]
name = "slack-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
serde_with = "2.0.1"
serde = "1.0.145"
serde_json = "1.0.85"
url = "2.3.1"
async-trait = "0.1.64"

## REQWEST ##
[dependencies.reqwest]
version = "0.11.0"
features = ["json", "multipart"]
